-- The host's voice.
--
-- Speech is generated by a paid service, so every line is generated once and
-- kept. The key is a hash of everything that shapes the audio (voice, model,
-- delivery, and the words), so the same line said the same way is free the
-- second time, for every player, forever.

CREATE TABLE voice_cache (
    hash         text PRIMARY KEY,
    voice        text        NOT NULL,
    model        text        NOT NULL,
    personality  text        NOT NULL DEFAULT '',
    text         text        NOT NULL,
    audio        bytea       NOT NULL,
    chars        int         NOT NULL,
    hits         int         NOT NULL DEFAULT 0,
    created_at   timestamptz NOT NULL DEFAULT now(),
    last_used_at timestamptz NOT NULL DEFAULT now()
);

-- Characters sent to the speech service, per day. This is what the daily budget
-- is checked against, so one busy session cannot spend a month's allowance.
CREATE TABLE voice_usage (
    day      date PRIMARY KEY,
    chars    int NOT NULL DEFAULT 0,
    requests int NOT NULL DEFAULT 0
);
